# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4317b1fe327fb0c171e832054ddb35553aa68b23c18bfce00d037a4f27bb9d9c3375c636255818943365044af6d2bf81eda25a79aedbf0f14afb1afeadd62650

test:
  secret_key_base: aaafeaef9f2de3bad5f3c02a1b3554913b3b3929f7821290f5b4bc9a1f192493ef7c3419e3726a7c7e8601ee210b1c0d4134c2f56c505953ad4ce4fc5ee6f46d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
